"""Build config/watchlist.yaml: a fixed large-cap control group + a rule-based small-cap sample.

Why a sample and not a hand-picked list: the research question is whether news sentiment
carries more information for *less-covered* companies. Hand-picking small caps tends to pick
the famous ones (retail favourites with lots of news), which biases the group towards exactly
the coverage it is supposed to lack. Instead the small-cap group is a random sample from the
S&P SmallCap 600, stratified so each sector of the large-cap group gets the same number of
names. The constituent snapshot and the seed are committed, so the list is reproducible.

    python scripts/build_watchlist.py            # print the YAML
    python scripts/build_watchlist.py --write    # overwrite config/watchlist.yaml
"""

from __future__ import annotations

import argparse
import csv
import random
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "data" / "sp600_constituents_2026-09.csv"
OUTPUT = ROOT / "config" / "watchlist.yaml"
SEED = 20260926
PER_SECTOR = 5

# Our sector label -> GICS sector in the S&P 600 snapshot.
SECTORS = {
    "technology": "Information Technology",
    "communication": "Communication Services",
    "consumer": "Consumer Discretionary",
    "financials": "Financials",
    "healthcare": "Health Care",
    "energy": "Energy",
}

# Control group: the most covered companies in each sector (hand-picked on purpose).
LARGE_CAPS = [
    ("AAPL", "Apple", "technology"),
    ("MSFT", "Microsoft", "technology"),
    ("NVDA", "Nvidia", "technology"),
    ("GOOGL", "Alphabet / Google", "communication"),
    ("META", "Meta Platforms", "communication"),
    ("AMZN", "Amazon", "consumer"),
    ("TSLA", "Tesla", "consumer"),
    ("JPM", "JPMorgan Chase", "financials"),
    ("LLY", "Eli Lilly", "healthcare"),
    ("XOM", "Exxon Mobil", "energy"),
]

_SUFFIX = re.compile(
    r",?\s+(Inc\.?|Corp\.?|Corporation|Company|Co\.?|Ltd\.?|Limited|plc|PLC|Holdings?|Group)$"
)


def short_name(security: str) -> str:
    """'Axcelis Technologies Inc.' -> 'Axcelis Technologies' (the LLM matches on names)."""
    name = security.strip()
    for _ in range(2):
        name = _SUFFIX.sub("", name).strip()
    return name


def load_pool(path: Path = SNAPSHOT) -> dict[str, list[tuple[str, str]]]:
    """Eligible (ticker, name) per sector: one share class per company, plain tickers only."""
    pool: dict[str, list[tuple[str, str]]] = {label: [] for label in SECTORS}
    gics_to_label = {v: k for k, v in SECTORS.items()}
    with open(path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            label = gics_to_label.get(row["GICS Sector"])
            symbol, security = row["Symbol"].strip(), row["Security"].strip()
            if label is None or "." in symbol or "(Class" in security:
                continue
            pool[label].append((symbol, short_name(security)))
    return pool


def sample_small_caps(
    pool: dict[str, list[tuple[str, str]]], per_sector: int = PER_SECTOR, seed: int = SEED
) -> list[tuple[str, str, str]]:
    rng = random.Random(seed)
    picked = []
    for label in SECTORS:  # fixed order -> same draw for the same seed
        candidates = sorted(pool[label])
        for ticker, name in rng.sample(candidates, per_sector):
            picked.append((ticker, name, label))
    return picked


def render(small_caps: list[tuple[str, str, str]]) -> str:
    def line(ticker: str, name: str, group: str, sector: str) -> str:
        quoted = '"' + name.replace('"', "'") + '",'
        return (
            f"  - {{ticker: {ticker + ',':<6} name: {quoted:<34} "
            f"group: {group + ',':<14} sector: {sector}}}"
        )

    out = [
        "# GENERATED by scripts/build_watchlist.py - edit the script, not this file.",
        "#",
        "# Universe for the news -> price experiment. `group` is the variable under study:",
        "# does news sentiment carry more information for companies that fewer analysts and",
        "# algorithms follow?",
        "#   large_cap:     the most covered company(ies) per sector - control group.",
        f"#   small_mid_cap: random sample, {PER_SECTOR} per sector, from the S&P SmallCap 600",
        f"#                  ({SNAPSHOT.name}, seed {SEED}) - no hand-picking.",
        "benchmark: SPY",
        "",
        "tickers:",
        "  # " + "-" * 64 + " large caps (control)",
    ]
    out += [line(t, n, "large_cap", s) for t, n, s in LARGE_CAPS]
    out.append("")
    out.append("  # " + "-" * 64 + " small caps (S&P 600 sample)")
    out += [line(t, n, "small_mid_cap", s) for t, n, s in small_caps]
    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help=f"overwrite {OUTPUT}")
    args = parser.parse_args()
    text = render(sample_small_caps(load_pool()))
    if args.write:
        OUTPUT.write_text(text, encoding="utf-8")
        print(f"Wrote {OUTPUT}")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
